let trainer = {
    "Shaun Stafford": {
        name: "Shaun Stafford",
        id: 1,
        type: "gym",
        image: "/assets/trainer/shaunStafford.png",
        expertise: "Fat loss & Body Recomposition",
        phone: "0123456789",
        email: "example@gmai.com",
        rating: "4.3/5",
        favorite: false,
    },
    "Hong Anh": {
        name: "Hong Anh",
        id: 2,
        type: "yoga",
        image: "/assets/trainer/hongAnh.png",
        expertise: "Yoga Instructor",
        phone: "0123456789",
        email: "example@gmai.com",
        rating: "4.3/5",
        favorite: false,
    },
    "Minh Hoang": {
        name: "Minh Hoang",
        id: 3,
        type: "boxing",
        image: "/assets/trainer/minhHoang.png",
        expertise: "Boxing",
        phone: "0123456789",
        email: "example@gmai.com",
        rating: "4.3/5",
        favorite: false,
    },
    "Anh Huy": {
        name: "Anh Huy",
        id: 4,
        type: "press",
        image: "/assets/trainer/anhHuy.png",
        expertise: "Press",
        phone: "0123456789",
        email: "example@gmai.com",
        rating: "4.3/5",
        favorite: false,
    },
    "Knight Wolf": {
        name: "Knight Wolf",
        id: 5,
        type: "press",
        image: "/assets/trainer/mattRoberts.png",
        expertise: "Swimming Instructor",
        rating: "4.3/5",
        phone: "0123456789",
        email: "example@gmai.com",
        favorite: false,
    },
    "Kayla Itsines": {
        name: "Kayla Itsines",
        id: 6,
        type: "press",
        image: "/assets/trainer/kaylaItsines.png",
        expertise: "Press",
        phone: "0123456789",
        email: "example@gmai.com",
        rating: "4.3/5",
        favorite: false,
    },
};